services:
  backend:
    build: ./backend
    ports: 
    - "5000:5000"
    
  device_1:
    build: ./device
    environment:
      - DEVICE_ID=device_1
  
  device_2:
    build: ./device
    environment:
      - DEVICE_ID=device_2
  
  device_3:
    build: ./device
    environment:
      - DEVICE_ID=device_3
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    expose: 
      - "9090"
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"